## Day 4 file operation::

In [13]:
import pandas as pd
f = open("data46.csv","w")
f.write("""10-20
30-40
50-60
70-80
90-15
11-12
13-13
4-6
34-65
32-56""")
f.close()

In [8]:
df = pd.read_csv("data46.csv",sep="-",names=["num1","num2"])

In [14]:
df["sum"]=df["num1"]+df["num2"]
df["avg"]=df["sum"]/2

df.to_csv("out.csv")

## Question 2

In [ ]:
import pandas as pd

f = open("data47.csv","w")  # if i using diffrenct dir need to specify liek (r"c:\\that\\this\\data.csv") here r is raw string
f.write("""num1,num2
10,20
30,40
50,a
60,70
80,b
90,15
c,25
10,15""")
f.close()
df = pd.read_csv("data47.csv")

df = df.replace(["a","b","c"], 0)
df["num1"]=df["num1"].astype(int)
df["num2"]=df["num2"].astype(int)


df["sum"] = df["num1"] + df["num2"]
df["avg"] = df["sum"] / 2

print(df)
df.to_csv("out47.csv")

## Question 3

In [40]:
f=open("data48.csv",'w')
f.write("""num1,num2
10,20
30,40
50,
60,70
80,
90,15
,25
10,15
11,
,
25,5
0,
,
11,12""")
df=pd.read_csv("data48.csv")

In [41]:
df = df.fillna(0)

In [37]:
df["num1"]=df["num1"].astype(int)
df["num2"]=df["num2"].astype(int)

In [ ]:
df.info()

In [ ]:

df["sum"]=df["num1"]+df["num2"]
df["avg"]=df["sum"]/2
print(df)
df.to_csv("out48.csv")

## Question 4

In [106]:
import pandas as pd
f = open("data49.csv","w")

f.write("""name,dept
ravi,sales
manu,purch
hari,accts""")
f.close()

In [107]:
df = pd.read_csv("data49.csv",sep=",")
df

   name   dept
0  ravi  sales
1  manu  purch
2  hari  accts

In [108]:
one_hot = pd.get_dummies(df["dept"],dtype=int)  # this is called one-hot encoding
print(one_hot)

   accts  purch  sales
0      0      0      1
1      0      1      0
2      1      0      0

In [109]:
final= df.join(one_hot)
final

   name   dept  accts  purch  sales
0  ravi  sales      0      0      1
1  manu  purch      0      1      0
2  hari  accts      1      0      0

In [ ]:
# help(pd.get_dummies(df))  is used to see the ________

In [110]:
final= final.drop(["dept"],axis=1)

In [111]:
# mapping

df["dept"] =  df["dept"].map({"sales":1,"punch":2,"accts":3})

## Question 5

In [126]:
import pandas as pd

f = open("data50.csv","w")
f.write("""name  dept
ravi  sales
manu  purch
hari  accts
ranjan  finan""")
f.close()

df = pd.read_csv("data50.csv", sep="\s+")

df1 = df.copy()
df1["name"] = df1["name"].apply(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
print(df1)

# Expected2 (all upper case)

df2 = df.copy()
df2["name"] = df2["name"].str.upper()
df2["dept"] = df2["dept"].str.upper()

print(df2)

     name   dept
0    RavI  sales
1    ManU  purch
2    HarI  accts
3  RanjaN  finan
     name   dept
0    RAVI  SALES
1    MANU  PURCH
2    HARI  ACCTS
3  RANJAN  FINAN

## Question 5

In [133]:
f=open("data61.csv","w")
f.write("""
fullname
a-b-c 
x-y-z
p-q-r
arun-kumar-sharma""")
f.close()
df=pd.read_csv("data61.csv")
df

            fullname
0             a-b-c
1              x-y-z
2              p-q-r
3  arun-kumar-sharma

In [136]:
df[["first","mid","last"]] = df["fullname"].str.split("-", expand=True)

df

            fullname first    mid    last
0             a-b-c      a      b      c
1              x-y-z     x      y       z
2              p-q-r     p      q       r
3  arun-kumar-sharma  arun  kumar  sharma

## last exercise pandas

In [173]:

f=open("data62.csv","w")
f.write("""name,dob
tamil,09-10-2003
vaish,24-08-2003
vikra,10-08-2004
madan,13-06-2005""")
f.close()

In [174]:
df=pd.read_csv("data62.csv")
df

    name         dob
0  tamil  09-10-2003
1  vaish  24-08-2003
2  vikra  10-08-2004
3  madan  13-06-2005

In [ ]:
df["dob"] = pd.to_datetime(df["dob"])
today = pd.Timestamp.today()
df["age"] = ((today - df["dob"]).dt.days / 365)

df

## Business Analysis